// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Node struct {
	ID          int64
	Namespace   string
	Name        string
	Image       string
	Cmd         string
	ContainerID sql.NullString
	DeletedAt   sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
